# Generated by Django 2.1.7 on 2019-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='approve_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
